[mkvlayer]
num_of_layer = 40
layer_type = 'GIVEN'
infname  = './_vgrid_40L_exp.dat'
outfname = './vgrid40test.dat'

[mkmnginfo]
rlevel  = 1
prc_num = 8
output_fname = './rl01-prc000008.toml'

[admparam]
glevel  = 5
rlevel  = 1	
vlayer  = 1
rgnmngfname = './prep.toml'
ADM_HGRID_SYSTEM = 'ICO'
debug = false

[param_mkgrd]
mkgrd_dospring    = false  # true
mkgrd_doprerotate = false
mkgrd_dostretch   = false
mkgrd_doshrink    = false
mkgrd_dorotate    = false
mkgrd_in_basename = ''
mkgrd_in_io_mode  = ''
mkgrd_out_basename = 'ADVANCED'
mkgrd_out_io_mode  = 'ADVANCED'
mkgrd_spring_beta      =  1.15  # parameter beta for spring dynamics
mkgrd_prerotation_tilt =  0.0  # [deg] 
mkgrd_stretch_alpha    =  1.00  # parameter alpha for stretch   
mkgrd_shrink_level     =  0.0  # shrink level (only for 1-diamond experiment) 
mkgrd_rotation_lon     =  0.0  # [deg] 
mkgrd_rotation_lat     = 90.0  # [deg] 
mkgrd_precision_single = false

[param_io]
h_source = 'src path' 
h_institute = 'pyNICAM-DC team'
io_log_basename = 'msg'
io_log_suppress = false
io_log_allnode = true
io_log_nml_suppress = false
io_aggregate = false

[cnstparam]

[rgnmngparam]
RGNMNG_in_fname='rl01-prc000008.toml'
RGNMNG_out_fname='tempout'

