Title = "mnginfo for rlevel= 0, process number= 5"

[RGN_INFO]
NUM_OF_RGN = 10

[PROC_INFO]
NUM_OF_PROC = 5
NUM_OF_MNG = 2

[RGN_LINK_INFO.000000]
RGNID = 0
SW = [ 5, 2,]
NW = [ 4, 2,]
NE = [ 1, 1,]
SE = [ 9, 1,]

[RGN_LINK_INFO.000001]
RGNID = 1
SW = [ 9, 2,]
NW = [ 0, 2,]
NE = [ 2, 1,]
SE = [ 8, 1,]

[RGN_LINK_INFO.000002]
RGNID = 2
SW = [ 8, 2,]
NW = [ 1, 2,]
NE = [ 3, 1,]
SE = [ 7, 1,]

[RGN_LINK_INFO.000003]
RGNID = 3
SW = [ 7, 2,]
NW = [ 2, 2,]
NE = [ 4, 1,]
SE = [ 6, 1,]

[RGN_LINK_INFO.000004]
RGNID = 4
SW = [ 6, 2,]
NW = [ 3, 2,]
NE = [ 0, 1,]
SE = [ 5, 1,]

[RGN_LINK_INFO.000005]
RGNID = 5
SW = [ 6, 3,]
NW = [ 4, 3,]
NE = [ 0, 0,]
SE = [ 9, 0,]

[RGN_LINK_INFO.000006]
RGNID = 6
SW = [ 7, 3,]
NW = [ 3, 3,]
NE = [ 4, 0,]
SE = [ 5, 0,]

[RGN_LINK_INFO.000007]
RGNID = 7
SW = [ 8, 3,]
NW = [ 2, 3,]
NE = [ 3, 0,]
SE = [ 6, 0,]

[RGN_LINK_INFO.000008]
RGNID = 8
SW = [ 9, 3,]
NW = [ 1, 3,]
NE = [ 2, 0,]
SE = [ 7, 0,]

[RGN_LINK_INFO.000009]
RGNID = 9
SW = [ 5, 3,]
NW = [ 0, 3,]
NE = [ 1, 0,]
SE = [ 8, 0,]

[RGN_MNG_INFO.000000]
PEID = 0
NUM_OF_MNG = 2
MNG_RGNID = [ 0, 1,]

[RGN_MNG_INFO.000001]
PEID = 1
NUM_OF_MNG = 2
MNG_RGNID = [ 2, 3,]

[RGN_MNG_INFO.000002]
PEID = 2
NUM_OF_MNG = 2
MNG_RGNID = [ 4, 5,]

[RGN_MNG_INFO.000003]
PEID = 3
NUM_OF_MNG = 2
MNG_RGNID = [ 6, 7,]

[RGN_MNG_INFO.000004]
PEID = 4
NUM_OF_MNG = 2
MNG_RGNID = [ 8, 9,]
